$ErrorActionPreference = "Stop"
$gh = "C:\Program Files\GitHub CLI\gh.exe"
$repo = "WonahGodwino/e-restaurant"

$items = @(
  @{ t = "Add allergen compliance for UK, EU, and US"; b = "Priority: High`n`nImplement structured allergen support across the menu, cart, and checkout to meet customer expectations and regulatory norms across UK, EU, and US markets.`n`nAcceptance criteria:`n- Each menu item stores allergen metadata in structured form`n- UK/EU 14 allergens are supported`n- US major allergens including sesame are supported`n- Allergen warnings display on menu item detail, cart, and checkout`n- A configurable cross-contamination disclaimer is available`n- Admin can update allergen data per item" },
  @{ t = "Add dietary and religious food filters"; b = "Priority: High`n`nAdd dietary and religious suitability tags and customer-facing filters for common ordering needs in African restaurant menus.`n`nAcceptance criteria:`n- Menu items can be tagged as halal, vegetarian, vegan, gluten-free, dairy-free, nut-free, and pork-free`n- Customers can filter by one or more dietary tags`n- Dish cards visibly display active dietary badges`n- Admin can manage dietary tags per item`n- Filters work together with category and search" },
  @{ t = "Add delivery zone, postcode, and fee rules"; b = "Priority: High`n`nSupport delivery eligibility rules by postcode or service area and calculate fees and minimum order requirements.`n`nAcceptance criteria:`n- Admin can define delivery zones or postcode coverage`n- Checkout validates whether an address is serviceable`n- Delivery fee can be configured per zone`n- Minimum order amount can be configured per zone`n- Invalid delivery addresses are blocked before payment" },
  @{ t = "Add scheduled delivery and pickup slots"; b = "Priority: High`n`nAllow customers to choose ASAP ordering or a scheduled pickup or delivery time.`n`nAcceptance criteria:`n- Checkout offers ASAP and scheduled ordering options`n- Available slots respect configured business hours`n- Cutoff times are enforced`n- Selected slot is stored with the order`n- Admin can configure service windows" },
  @{ t = "Add modifier and customization engine"; b = "Priority: High`n`nSupport dish modifiers and add-ons common in African cuisine ordering, such as swallow choice, spice level, protein choice, and sides.`n`nAcceptance criteria:`n- Menu items support one or more modifier groups`n- Modifier groups support single-select and multi-select modes`n- Modifiers can change price`n- Selected modifiers are stored in the order`n- Cart and admin order view display chosen modifiers clearly" },
  @{ t = "Add customer order tracking experience"; b = "Priority: High`n`nProvide a customer-facing order tracking flow that reflects status changes after checkout.`n`nAcceptance criteria:`n- Customer can view order status after order placement`n- Statuses include received, preparing, ready, out for delivery, and delivered`n- Status changes are visible in near real time or via reliable polling`n- Staff can update order status from admin workflow`n- Order timeline is stored for display" },
  @{ t = "Harden production payment flow"; b = "Priority: High`n`nMove from demo-safe fallback behavior to a secure production-ready payment flow with robust error handling.`n`nAcceptance criteria:`n- Real payment provider flow works when configured`n- Failed payments do not leave inconsistent order state`n- Customers see clear payment failure messages`n- Payment attempts and failures are logged`n- Checkout supports secure payment requirements such as 3DS where applicable" },
  @{ t = "Add customer confirmation notifications"; b = "Priority: High`n`nSend customer notifications for order confirmation and important order updates.`n`nAcceptance criteria:`n- Confirmation email is sent after successful order placement`n- Email includes order number, items, totals, and delivery or pickup information`n- Notification sending failures are logged`n- Notification templates are configurable or easy to maintain`n- Architecture allows optional future SMS or WhatsApp support" },
  @{ t = "Add VAT, sales tax, and receipt compliance"; b = "Priority: High`n`nSupport region-aware tax calculation and receipt rendering for UK, US, and EU use cases.`n`nAcceptance criteria:`n- Order model stores subtotal, tax, delivery fee, discount, and total`n- UK VAT can be configured and displayed`n- US sales tax can be configured and displayed`n- EU VAT-style breakdown can be configured and displayed`n- Receipts reflect the correct configured tax mode" },
  @{ t = "Add privacy and consent management"; b = "Priority: High`n`nAdd privacy consent and policy handling aligned with UK GDPR, EU GDPR, and practical US privacy expectations.`n`nAcceptance criteria:`n- Privacy policy link is visible in customer-facing pages`n- Consent banner or preference flow exists where needed`n- Consent choices can be recorded`n- Data request handling path is documented for support or admin`n- Privacy-related configuration is manageable without code changes where practical" },
  @{ t = "Add legal policy pages"; b = "Priority: High`n`nAdd legal and operational policy pages required for professional restaurant operations.`n`nAcceptance criteria:`n- Privacy Policy page exists`n- Terms and Conditions page exists`n- Delivery Policy page exists`n- Refund Policy page exists`n- Allergy Disclaimer page exists`n- Pages are linked in footer and relevant checkout areas" },
  @{ t = "Add accessibility improvements to WCAG 2.2 AA baseline"; b = "Priority: High`n`nImprove the customer and admin interfaces to meet a practical WCAG 2.2 AA baseline.`n`nAcceptance criteria:`n- All interactive elements are keyboard accessible`n- Forms have correct labels and accessible error messages`n- Visible focus states exist across the application`n- Color contrast passes baseline accessibility checks`n- Core pages are navigable with screen readers" },
  @{ t = "Add age-restricted item support"; b = "Priority: Medium`n`nAdd optional support for age-restricted products such as alcohol if these are introduced later.`n`nAcceptance criteria:`n- Menu items can be flagged as age-restricted`n- Customers see a warning for age-restricted items`n- Checkout can enforce age confirmation`n- Admin can manage restriction status per item" },
  @{ t = "Add admin audit logging"; b = "Priority: High`n`nTrack sensitive admin and staff actions for accountability and operational debugging.`n`nAcceptance criteria:`n- Menu edits are logged`n- Stock and threshold changes are logged`n- User management actions are logged`n- Order status changes are logged`n- Each log entry includes actor, action, target, and timestamp" },
  @{ t = "Add promo codes and discount rules"; b = "Priority: Medium`n`nEnable promotional discounting to support customer acquisition and campaigns.`n`nAcceptance criteria:`n- Admin can create promo codes`n- Codes can have expiry dates and usage limits`n- Minimum spend can be enforced`n- Discounts are shown clearly in cart and checkout`n- Order records store applied discount information" },
  @{ t = "Add loyalty and referral program"; b = "Priority: Medium`n`nIntroduce repeat-purchase incentives with loyalty points and referrals.`n`nAcceptance criteria:`n- Customers can earn loyalty points from orders`n- Points can be redeemed against future orders`n- Referral codes can be generated and tracked`n- Admin can configure earning and redemption rules" },
  @{ t = "Add reservations and catering requests"; b = "Priority: Medium`n`nSupport reservation requests and large-order or catering enquiries.`n`nAcceptance criteria:`n- Customers can submit reservation requests with party size, date, and time`n- Customers can submit catering requests with event details and notes`n- Admin receives alerts for new requests`n- Requests are visible in an admin management view" },
  @{ t = "Add reviews and ratings system"; b = "Priority: Medium`n`nAllow customers to leave feedback after completed orders.`n`nAcceptance criteria:`n- Customers can rate completed orders`n- Customers can submit written reviews`n- Admin can moderate reviews`n- Average ratings can be displayed on restaurant or dish views" },
  @{ t = "Add multi-currency support"; b = "Priority: Medium`n`nAdd support for multiple customer-facing currencies such as GBP, USD, and EUR.`n`nAcceptance criteria:`n- Store supports configurable base currency`n- Prices can be displayed in GBP, USD, and EUR`n- Currency formatting is locale aware`n- Order totals remain internally consistent through checkout" },
  @{ t = "Add African cuisine discovery features"; b = "Priority: Medium`n`nImprove menu discovery and storytelling for African cuisine with origin and region tags.`n`nAcceptance criteria:`n- Dishes can be tagged by African region`n- Customers can filter by region such as West African, East African, North African, and Southern African`n- Dish details can show short origin or cultural notes`n- Admin can manage region tags and notes" },
  @{ t = "Add kitchen display and printable ticket workflow"; b = "Priority: Medium`n`nProvide a kitchen-friendly order management flow for preparation and ticket printing.`n`nAcceptance criteria:`n- New orders appear in a kitchen-focused view`n- Order tickets clearly show items and modifiers`n- Staff can move orders to preparing and ready states`n- Printable ticket layout is available" },
  @{ t = "Add inventory deduction and restock history"; b = "Priority: Medium`n`nExtend stock management with auditable stock movement tracking.`n`nAcceptance criteria:`n- Stock deductions occur on order creation or confirmation as configured`n- Restock actions are stored with quantity and timestamp`n- Admin can review stock movement history`n- Negative stock is prevented by validation" },
  @{ t = "Add POS and webhook integrations"; b = "Priority: Medium`n`nSupport webhook-based integration with external platforms such as POS systems, Shopify, or delivery services.`n`nAcceptance criteria:`n- Incoming webhook events can update order state safely`n- Failed webhook processing is logged`n- Retry handling exists for transient failures`n- External reference IDs are stored where relevant" },
  @{ t = "Add analytics and business reporting dashboard"; b = "Priority: Medium`n`nProvide owners and managers with reporting on revenue, product performance, and operations.`n`nAcceptance criteria:`n- Dashboard shows sales totals by period`n- Dashboard shows order counts and average order value`n- Dashboard shows top-selling dishes`n- Dashboard shows stockout or low-stock trends`n- Dashboard shows cancellations and delivery performance metrics" },
  @{ t = "Add customer support and order management tools"; b = "Priority: Medium`n`nImprove support workflows for staff handling order issues and customer follow-up.`n`nAcceptance criteria:`n- Admin can search orders by order ID, customer, and date`n- Staff can resend order confirmations`n- Staff can add internal notes to orders`n- Staff can view order event timeline and status history`n- Staff can update order status from a support view" }
)

$urls = @()
foreach ($i in $items) {
  $url = & $gh issue create --repo $repo --title $i.t --body $i.b --label feature
  $urls += $url
}

$urls | ForEach-Object { Write-Output $_ }
